title: |
  {{- range .alerts -}}
  {{- if eq $.status "firing" -}}
  ðŸš¨ {{ .annotations.summary }}
  {{- else -}}
  âœ… {{ .annotations.summary | replace "is down" "is up" | replace "failed" "recovered" }}
  {{- end -}}
  {{- end }}
message: |
  {{- range .alerts }}
  Starts: {{ .startsAt | date "2006-01-02 15:04:05" }}
  Instance: {{ .labels.instance }}
  {{- end }}
priority: |
  {{- if eq .status "firing" -}}
  4
  {{- else -}}
  3
  {{- end }}
